---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: metallb
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: scratch
