#install Traefik v2

defaultNamespace: traefik
helm:
  releaseName: traefik
  repo: https://helm.traefik.io/traefik
  chart: traefik
  values:
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
#TODO: ACME/Lets Encrypt
